# Generated by Django 5.1.1 on 2024-10-09 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('data', models.DateField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('fechado', 'Fechado'), ('cancelado', 'Cancelado'), ('concluido', 'Concluido'), ('em_andamento', 'Em Andamento'), ('pendente', 'Pendente'), ('reaberto', 'Reaberto'), ('resolvido', 'Resolvido'), ('rejeitado', 'Rejeitado'), ('suspensao', 'Suspensão'), ('suspensao_permanente', 'Suspensão Permanente'), ('suspensao_temporaria', 'Suspensão Temporária')], max_length=20)),
                ('progresso', models.FloatField(default=0.0)),
            ],
        ),
    ]
